### ISSUE TITLE
Concurrency issue  and restarted (only in one pod)

### ISSUE THREAD

**Issue by shamlymajeed** [metno/go-mms#352]
log from mms-sidecar
```
fatal error: 2023/12/14 16:52:22 Post ended
concurrent map iteration and map write

goroutine 100 [running]:
github.com/metno/go-mms/internal/server.(*Productstatus).UpdateMetrics(0xc0001a86e0)
	/build/app/internal/server/productstatus.go:62 +0xc7
main.startEventLoop.func1()
	/build/app/cmd/mmsd/main.go:472 +0x65
created by main.startEventLoop
	/build/app/cmd/mmsd/main.go:467 +0x18a

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f0c68dac398, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000036100?, 0x4?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000036100)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc000036100)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc001519bc0)
	/usr/local/go/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc001519bc0)
	/usr/local/go/src/net/tcpsock.go:297 +0x3d
net/http.(*Server).Serve(0xc0003ca0f0, {0x150bbe0, 0xc001519bc0})
	/usr/local/go/src/net/http/server.go:3059 +0x385
net/http.(*Server).ListenAndServe(0xc0003ca0f0)
	/usr/local/go/src/net/http/server.go:2988 +0x7d
main.startWebServer(0xc0001b22d0, {0xc0003df3e0, 0xc}, 0x0, {0x10feb79, 0x8}, {0x10fce62, 0x7})
	/build/app/cmd/mmsd/main.go:501 +0x16c
main.main.func2(0xc0003ce6e0?)
	/build/app/cmd/mmsd/main.go:306 +0x1189
github.com/urfave/cli/v2.(*Command).Run(0xc0003ce6e0, 0xc00031d280, {0xc000036080, 0x8, 0x8})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*App).RunContext(0xc0003cc000, {0x150ca88?, 0xc00003c058}, {0xc000036080, 0x8, 0x8})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
	/build/app/cmd/mmsd/main.go:412 +0x1c30

goroutine 34 [select, 211 minutes]:
database/sql.(*DB).connectionOpener(0xc0002fadd0, {0x150ca50, 0xc0003115e0})
	/usr/local/go/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:791 +0x18d

goroutine 35 [select, 211 minutes]:
database/sql.(*DB).connectionOpener(0xc0002faf70, {0x150ca50, 0xc000311630})
	/usr/local/go/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:791 +0x18d

goroutine 101 [chan receive, 33 minutes]:
main.startEventLoop.func2()
	/build/app/cmd/mmsd/main.go:481 +0x45
created by main.startEventLoop
	/build/app/cmd/mmsd/main.go:478 +0x207

goroutine 34598 [IO wait]:
internal/poll.runtime_pollWait(0x7f0c68dabfd8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0001e6100?, 0xc0004d0000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001e6100, {0xc0004d0000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0001e6100, {0xc0004d0000?, 0x4ee646?, 0x7f0c68dac0c0?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0001ae0c8, {0xc0004d0000?, 0x0?, 0xc00019c728?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc00019c720, {0xc0004d0000, 0x1000, 0x1000})
	/usr/local/go/src/net/http/server.go:782 +0x171
bufio.(*Reader).fill(0xc0012fe8a0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0012fe8a0, 0x4)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*conn).serve(0xc00020c2d0, {0x150caf8, 0xc00189d290})
	/usr/local/go/src/net/http/server.go:2030 +0x77c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed

goroutine 34589 [IO wait]:
internal/poll.runtime_pollWait(0x7f0c68dabee8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00048c600?, 0xc0004fd5a1?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00048c600, {0xc0004fd5a1, 0x1, 0x1})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc00048c600, {0xc0004fd5a1?, 0xf2b69596df9c1?, 0xc001480690?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000014930, {0xc0004fd5a1?, 0x1963542e?, 0x412720?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc0004fd590)
	/usr/local/go/src/net/http/server.go:674 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:670 +0xca

goroutine 34588 [runnable]:
context.(*cancelCtx).cancel(0xc001481310, 0x1, {0x1505760, 0xc0000fe0e0}, {0x0?, 0x0?})
	/usr/local/go/src/context/context.go:473 +0x1e5
context.WithCancel.func1()
	/usr/local/go/src/context/context.go:240 +0x35
net/http.(*conn).serve(0xc0001b3320, {0x150caf8, 0xc00189d290})
	/usr/local/go/src/net/http/server.go:1997 +0x633
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

**Comment by mortenwh** [comment]
@shamlymajeed - where are we with this one?
